language: ruby
cache: bundler
rvm:
- ruby-2.2.2
env:
  - DB=sqlite
services:
- postgresql 
before_script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
script:
  - CODECLIMATE_REPO_TOKEN=c97988e6ff0969f56fc41dd6ca3c42fe42b0a0ee8ea8a4a96066f3e1c042256b bundle exec rake cucumber
  - bundle exec rake spec

addons:
  code_climate:
    repo_token: c97988e6ff0969f56fc41dd6ca3c42fe42b0a0ee8ea8a4a96066f3e1c042256b